language: java
jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - docker build -t bgpark82/game-math -f ./math/Dockerfile .
  - docker build -t bgpark82/game-score -f ./score/Dockerfile .

  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bgpark82/game-math
  - docker push bgpark82/game-score