version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:085853160041:task-definition/game-math:12"
        LoadBalancerInfo:
          ContainerName: "game-math"
          ContainerPort: "7001"
        PlatformVersion: "LATEST"
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:085853160041:task-definition/game-math:12"
        LoadBalancerInfo:
          ContainerName: "game-score"
          ContainerPort: "7002"
        PlatformVersion: "LATEST"
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:085853160041:task-definition/game-math:12"
        LoadBalancerInfo:
          ContainerName: "game-eureka-server"
          ContainerPort: "8761"
        PlatformVersion: "LATEST"
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:085853160041:task-definition/game-math:12"
        LoadBalancerInfo:
          ContainerName: "game-gateway"
          ContainerPort: "80"
        PlatformVersion: "LATEST"