version: '3'
services:

  math:
    image: bgpark82/game-math
    build:
      context: .
      dockerfile: ./math/Dockerfile
    mem_limit: 350m
    ports:
      - '7001:7001'
    environment:
      SPRING_PROFILES_ACTIVE: local

  score:
    image: bgpark82/game-score
    build:
      context: .
      dockerfile: ./score/Dockerfile
    mem_limit: 350m
    ports:
      - '7002:7002'
    environment:
      SPRING_PROFILES_ACTIVE: local

  eureka-server:
    image: bgpark82/game-eureka-server
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    mem_limit: 350m
    ports:
      - '8761:8761'