version: '3'
services:

  math:
    image: bgpark82/game-math
    build: math
    mem_limit: 350m
    ports:
      - '7001:7001'
    environment:
      SPRING_PROFILES_ACTIVE: docker

  score:
    image: bgpark82/game-score
    build: score
    mem_limit: 350m
    ports:
      - '7002:7002'
    environment:
      SPRING_PROFILES_ACTIVE: docker

  eureka-server:
    image: bgpark82/game-eureka-server
    build: eureka-server
    mem_limit: 350m
    ports:
      - '8761:8761'