version: '3'
services:

  math:
    image: bgpark82/game-math
    build: math
    mem_limit: 350m
    ports:
      - '7001:7001'


  score:
    image: bgpark82/game-score
    build: score
    mem_limit: 350m
    ports:
      - '7002:7002'
