server:
  port: 7002

logging:
  level:
    root: info
    com.bgpark.game: debug

spring:
  h2:
    console:
      enabled: true
  application:
    name: score

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

---

server:
  port: 7002

spring:
  profiles: docker