server:
  port: 7001

logging:
  level:
    root: info
    com.bgpark.game: debug

spring:
  h2:
    console:
      enabled: true

spring:datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: docker

server:
  port: 7001

app:
  score:
    host: localhost
    port: 7002
